import type { DesktopStorageClient } from '../desktop-storage-client'
import type { DesktopStorageDomains } from '../desktop-storage-contracts'
import type { replaceDocumentGraph } from '../desktop-storage-knowledge-operations'

export type Awaitable<T> = T | Promise<T>
type DomainPort<T> = { [K in keyof T]: T[K] extends (...args: infer A) => infer R ? (...args: A) => Awaitable<Awaited<R>> : never }
export type KnowledgeStoragePort = DomainPort<Omit<DesktopStorageDomains['knowledge'], 'replaceEvidenceForDocument'>> & {
  externalStore: DomainPort<DesktopStorageDomains['external']>
  replaceDocumentGraph(...args: Parameters<typeof replaceDocumentGraph> extends [unknown, ...infer A] ? A : never): Awaitable<void>
}

/** Explicit domain calls; no live database or transaction callback crosses Main. */
export function createKnowledgeStoragePort(storage: Pick<DesktopStorageClient, 'call'>): KnowledgeStoragePort {
  return {
    createKnowledgeBase: (...args) => storage.call('knowledge', 'createKnowledgeBase', args),
    listKnowledgeBases: (...args) => storage.call('knowledge', 'listKnowledgeBases', args),
    getKnowledgeBaseCounts: (...args) => storage.call('knowledge', 'getKnowledgeBaseCounts', args),
    getKnowledgeBase: (...args) => storage.call('knowledge', 'getKnowledgeBase', args),
    saveExternalBinding: (...args) => storage.call('knowledge', 'saveExternalBinding', args),
    updateKnowledgeBase: (...args) => storage.call('knowledge', 'updateKnowledgeBase', args),
    updateKnowledgeSettings: (...args) => storage.call('knowledge', 'updateKnowledgeSettings', args),
    markKnowledgeChunkingRebuilt: (...args) => storage.call('knowledge', 'markKnowledgeChunkingRebuilt', args),
    markKnowledgeOntologyRebuilt: (...args) => storage.call('knowledge', 'markKnowledgeOntologyRebuilt', args),
    deleteKnowledgeBase: (...args) => storage.call('knowledge', 'deleteKnowledgeBase', args),
    createKnowledgeTask: (...args) => storage.call('knowledge', 'createKnowledgeTask', args),
    getKnowledgeTask: (...args) => storage.call('knowledge', 'getKnowledgeTask', args),
    getActiveKnowledgeTaskByDedupeKey: (...args) => storage.call('knowledge', 'getActiveKnowledgeTaskByDedupeKey', args),
    getKnowledgeTaskByEmbeddingJobId: (...args) => storage.call('knowledge', 'getKnowledgeTaskByEmbeddingJobId', args),
    listKnowledgeTasks: (...args) => storage.call('knowledge', 'listKnowledgeTasks', args),
    listActiveKnowledgeTasks: (...args) => storage.call('knowledge', 'listActiveKnowledgeTasks', args),
    updateKnowledgeTask: (...args) => storage.call('knowledge', 'updateKnowledgeTask', args),
    cancelKnowledgeTask: (...args) => storage.call('knowledge', 'cancelKnowledgeTask', args),
    interruptActiveKnowledgeTasks: (...args) => storage.call('knowledge', 'interruptActiveKnowledgeTasks', args),
    pruneKnowledgeTasks: (...args) => storage.call('knowledge', 'pruneKnowledgeTasks', args),
    upsertSource: (...args) => storage.call('knowledge', 'upsertSource', args),
    listSources: (...args) => storage.call('knowledge', 'listSources', args),
    listSourcesForSnapshot: (...args) => storage.call('knowledge', 'listSourcesForSnapshot', args),
    getSource: (...args) => storage.call('knowledge', 'getSource', args),
    removeSource: (...args) => storage.call('knowledge', 'removeSource', args),
    upsertDocument: (...args) => storage.call('knowledge', 'upsertDocument', args),
    getDocumentByParsedResultId: (...args) => storage.call('knowledge', 'getDocumentByParsedResultId', args),
    getDocument: (...args) => storage.call('knowledge', 'getDocument', args),
    listDocuments: (...args) => storage.call('knowledge', 'listDocuments', args),
    listDocumentsForSource: (...args) => storage.call('knowledge', 'listDocumentsForSource', args),
    listDocumentsForLibraryRebuild: (...args) => storage.call('knowledge', 'listDocumentsForLibraryRebuild', args),
    listDocumentsForSnapshot: (...args) => storage.call('knowledge', 'listDocumentsForSnapshot', args),
    getDocumentChunkCounts: (...args) => storage.call('knowledge', 'getDocumentChunkCounts', args),
    removeDocument: (...args) => storage.call('knowledge', 'removeDocument', args),
    removeEvidenceForDocument: (...args) => storage.call('knowledge', 'removeEvidenceForDocument', args),
    pruneUnreferencedGeneratedGraph: (...args) => storage.call('knowledge', 'pruneUnreferencedGeneratedGraph', args),
    listChunks: (...args) => storage.call('knowledge', 'listChunks', args),
    listChunksPage: (...args) => storage.call('knowledge', 'listChunksPage', args),
    getChunkForReference: (...args) => storage.call('knowledge', 'getChunkForReference', args),
    updateChunk: (...args) => storage.call('knowledge', 'updateChunk', args),
    deleteChunk: (...args) => storage.call('knowledge', 'deleteChunk', args),
    listContextChunks: (...args) => storage.call('knowledge', 'listContextChunks', args),
    replaceDocumentEmbeddings: (...args) => storage.call('knowledge', 'replaceDocumentEmbeddings', args),
    beginDocumentEmbeddingReplacement: (...args) => storage.call('knowledge', 'beginDocumentEmbeddingReplacement', args),
    beginPreparedDocumentEmbeddingReplacement: (...args) => storage.call('knowledge', 'beginPreparedDocumentEmbeddingReplacement', args),
    appendDocumentEmbeddingBatch: (...args) => storage.call('knowledge', 'appendDocumentEmbeddingBatch', args),
    appendPreparedDocumentEmbeddingBatch: (...args) => storage.call('knowledge', 'appendPreparedDocumentEmbeddingBatch', args),
    finishDocumentEmbeddingReplacement: (...args) => storage.call('knowledge', 'finishDocumentEmbeddingReplacement', args),
    discardDocumentEmbeddingReplacement: (...args) => storage.call('knowledge', 'discardDocumentEmbeddingReplacement', args),
    recordEmbeddingIndexError: (...args) => storage.call('knowledge', 'recordEmbeddingIndexError', args),
    getEmbeddingIndexState: (...args) => storage.call('knowledge', 'getEmbeddingIndexState', args),
    getLastEmbeddingIndexJob: (...args) => storage.call('knowledge', 'getLastEmbeddingIndexJob', args),
    saveEmbeddingIndexJob: (...args) => storage.call('knowledge', 'saveEmbeddingIndexJob', args),
    listEmbeddingIndexDocumentIds: (...args) => storage.call('knowledge', 'listEmbeddingIndexDocumentIds', args),
    countEmbeddingIndexDocuments: (...args) => storage.call('knowledge', 'countEmbeddingIndexDocuments', args),
    getEmbeddingIndexCoverage: (...args) => storage.call('knowledge', 'getEmbeddingIndexCoverage', args),
    getEmbeddingIndexDocument: (...args) => storage.call('knowledge', 'getEmbeddingIndexDocument', args),
    vectorSearch: ({ signal, ...input }) => storage.call('knowledge', 'vectorSearch', [input], { signal }),
    graphSearch: (...args) => storage.call('knowledge', 'graphSearch', args),
    hybridSearch: ({ signal, ...input }) => storage.call('knowledge', 'hybridSearch', [input], { signal }),
    hybridSearchWithDiagnostics: ({ signal, ...input }) => storage.call('knowledge', 'hybridSearchWithDiagnostics', [input], { signal }),
    search: (...args) => storage.call('knowledge', 'search', args),
    createEntity: (...args) => storage.call('knowledge', 'createEntity', args),
    getEntity: (...args) => storage.call('knowledge', 'getEntity', args),
    listEntities: (...args) => storage.call('knowledge', 'listEntities', args),
    findEntityByCanonicalName: (...args) => storage.call('knowledge', 'findEntityByCanonicalName', args),
    listEntitiesForIdentity: (...args) => storage.call('knowledge', 'listEntitiesForIdentity', args),
    updateEntity: (...args) => storage.call('knowledge', 'updateEntity', args),
    deleteEntity: (...args) => storage.call('knowledge', 'deleteEntity', args),
    createRelation: (...args) => storage.call('knowledge', 'createRelation', args),
    getRelation: (...args) => storage.call('knowledge', 'getRelation', args),
    listRelations: (...args) => storage.call('knowledge', 'listRelations', args),
    findRelationByIdentity: (...args) => storage.call('knowledge', 'findRelationByIdentity', args),
    updateRelation: (...args) => storage.call('knowledge', 'updateRelation', args),
    deleteRelation: (...args) => storage.call('knowledge', 'deleteRelation', args),
    createEvidence: (...args) => storage.call('knowledge', 'createEvidence', args),
    listEvidence: (...args) => storage.call('knowledge', 'listEvidence', args),
    listGraphSnapshot: (...args) => storage.call('knowledge', 'listGraphSnapshot', args),
    updateEvidence: (...args) => storage.call('knowledge', 'updateEvidence', args),
    deleteEvidence: (...args) => storage.call('knowledge', 'deleteEvidence', args),
    mergeEntities: (...args) => storage.call('knowledge', 'mergeEntities', args),
    publishDocument: (...args) => storage.call('knowledge', 'publishDocument', args),
    replaceDocumentGraph: (...args) => storage.call('knowledge', 'replaceDocumentGraph', args),
    externalStore: {
      getInstance: (...args) => storage.call('external', 'getInstance', args),
      listInstances: (...args) => storage.call('external', 'listInstances', args),
      saveInstance: (...args) => storage.call('external', 'saveInstance', args),
      deleteInstance: (...args) => storage.call('external', 'deleteInstance', args),
      getBinding: (...args) => storage.call('external', 'getBinding', args),
      hasBinding: (...args) => storage.call('external', 'hasBinding', args),
      getBindingsForInstance: (...args) => storage.call('external', 'getBindingsForInstance', args),
      listBindings: (...args) => storage.call('external', 'listBindings', args),
      saveBinding: (...args) => storage.call('external', 'saveBinding', args),
    }
  }
}
